### ISSUE TITLE
Indicate progress in tab in service ui

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-cloud-requests#105]
we had a feedback form request submitted asking to show a progress indicator in the tab for the service ui
we should explore having a custom favicon to represent this in the window tab

duplicate private issue: https://github.com/pulumi/pulumi-service/issues/9899

**Comment by WP-LKL** [comment]
👍

**Comment by kimberleyamackenzie** [comment]
This work was completed a bit ago in December 2022!
