### ISSUE TITLE
Allow OIDC authentication from github actions (or similar) instead of API keys

### ISSUE THREAD

**Issue by antifuchs** [pulumi/pulumi-cloud-requests#115]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We've recently started using OIDC authentication between github actions and AWS, which allows administering infrastructure without having to hardcode long-lived AWS API keys anywhere. This is really cool because it makes our security team happy: We already trust GHA, we trust AWS, they are configured to trust each other, and we can relax knowing that no secrets can leak that would allow an attacker access to our infra. 

[Here's a good blog](https://www.cloudquery.io/blog/keyless-access-to-aws-in-github-actions-with-oidc) post about how that works, and [here's some docs from github](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services).

The key thing here is that it's configurable on the AWS side what "sub" identity can access what IAM role: For example, we've configured the our "staging" admin role to be accessible by any reference being built, but the "production" admin role can only be accessed from our main branch.

It would be amazing if we could do the same for pulumi, instead of having to store a long-lived API token.

**Comment by HenryNguyen5** [comment]
This looks great, in addition to what's described above, I think the following would give more flexibility over auth:

So based on a OIDC JSON token that is provided from a github workflow, presented to the pulumi service, it can issue a short lived token (lets say <1hr, configurable), that has permissions based on either:
- the author of the PR
- approvers
- some combination of the above, in addition to stack tags
- claims within the token
- a custom supplied javascript function, a similar concept to https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html to implement custom authorization given a valid OIDC token

**Comment by EronWright** [comment]
A similar use-case is that of using a Kubernetes-issued OIDC token within a pod to authenticate to Pulumi Cloud. This would allow the [Pulumi Kubernetes Operator](https://www.pulumi.com/docs/using-pulumi/continuous-delivery/pulumi-kubernetes-operator/) to use the Pulumi Cloud state backend without the inconvenience of configuring an access token.

I imagine that one would create a Kubernetes Service Account (KSA) to serve as a Pulumi organization or team member. Kubernetes would issue an OIDC token representing the pod's service account using token projection (see [blog post](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-bound-service-account-tokens)). The audience of the token would be the Pulumi Cloud. The resultant token file would be used by the Pulumi CLI.

One would configure Pulumi Cloud to accept OIDC tokens issued by the Kubernetes cluster. Kubernetes does provide an OIDC discovery endpoint but it might not be accessible directly by Pulumi Cloud in all scenarios. It may be necessary to side-load the issuer data (JWKS) in some cases.

As mentioned by @antifuchs and @HenryNguyen5, one would also need to apply conditions to the tokens, e.g. to allow specific KSAs.

**Comment by jtmarmon** [comment]
Related: https://github.com/pulumi/esc/issues/198

**Comment by cleverguy25** [comment]
This is supported now!  https://www.pulumi.com/blog/oidc-trust-github-action/
