### ISSUE TITLE
Add a confirmation for the Deploy > Destroy action 

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-cloud-requests#125]
This is just a suggestion, but given the destructiveness of this action and how easy it is to misclick, it might be a good idea to have users confirm requests to destroy a stack before running the deployment, and/or provide them with some way to stop a destroy action that's already in progress.

**Comment by EvanBoyle** [comment]
Thanks, Christian. We're planning on adding this.

**Comment by kimberleyamackenzie** [comment]
This was fixed awhile back via https://github.com/pulumi/pulumi-service/issues/10936
