### ISSUE TITLE
Request: Allow org tokens to list and export audit logs

### ISSUE THREAD

**Issue by djgrove** [pulumi/pulumi-cloud-requests#135]
User wants to export audit logs using an organization token, portion of documentation is incorrect in indicating this is possible. Initially a [bug report](https://github.com/pulumi/service-requests/issues/131) was filed because it was unexpected that organization tokens cannot do this.

Ask is to expand the permissions of organization tokens to list and export audit logs.

**Comment by EvanBoyle** [comment]
Fixed via https://github.com/pulumi/pulumi-cloud-requests/issues/242
