### ISSUE TITLE
skip pending deployments in a queue

### ISSUE THREAD

**Issue by alexanderniebuhr** [pulumi/pulumi-cloud-requests#136]
- [ ] Design doc reviewed with the team
- [ ] Project plan reviewed with @EvanBoyle 

if multiple commits are pushed to an repository in an on-push scenario an deployment is triggered for every commit. The deployments run sequentially. If all the commits are on the same branch, the latest commit / deployment, will include all the changes of the commits / deployments before it.
I propose to add an configuration flag which enables skipping of pending deployments in a queue **except the current running** and the last one. We currently merge multiple PRs at a specific time range, and end up with 10s of deployments, restarting our services multiple times (which is uncessary). _some note copied over from slack:_

- we are currently interested in the push-to-deploy scenario, however I think having it configurable for different combinations of triggers would be great
- cancelled deployments should be still shown in the UI, GitHub Actions has an similar approach (see screenshot)

<img width="1139" alt="Screenshot 2022-11-09 at 06 26 32" src="https://user-images.githubusercontent.com/45965090/200746161-2f770f56-dc56-4ecb-abc0-af0c771d134a.png">

**Comment by EvanBoyle** [comment]
We could optionally make this configurable as well. There may be multi-step rollouts that depend on several updates being run in sequence. We did this recently with our MySQL 5.6 EOL upgrade.

**Comment by glena** [comment]
The feature was implemented and is already available in production. The documentation can be found here https://www.pulumi.com/docs/pulumi-cloud/deployments/reference/#skip-intermediate-deployments
