### ISSUE TITLE
[deployments] - Expose public API for setting/updating environment variables for a stack 

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-cloud-requests#141]
Expose a public API to set/update environment variables for a stack to allow credential rotation.

**Comment by eriklz** [comment]
This is useful as one way to allow temporary credentials to be used for deployment via a push from the cloud provider, in combination with deployments triggered via git.

**Comment by EvanBoyle** [comment]
Fixed by the deployment settings patch work.
