### ISSUE TITLE
Add TTL for the deployment service

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi-cloud-requests#149]
The deployment service looks really awesome to simplify some deploys, and it also looks very promising for ephemeral environments. To get the ephemeral environments it would be nice to be able to set up a TTL as you've described in the blog post on how it can be done. Instead of each one of us implementing the TTL stuff it would be really good if that could be provided from the service.

**Comment by EvanBoyle** [comment]
One important consideration is enforcement. There should be a way to specify organization settings on TTL defaults so that when you `pulumi stack init` it prompts you to accept the TTL or opt out.

**Comment by mastoj** [comment]
If possible I would like to specify the TTL when I trigger the deployment. Not sure what the organization setting would provide?

**Comment by EvanBoyle** [comment]
There are probably a bunch of different ways that we could model this workflow, each with pros and cons:

1. specify a TTL when the deployment is run
2. have a TTL as a property of the stack, any operation such as an update resets the TTL
3. scheduled deployments (ie create a deployment `operation: destroy` but let it sit in the queue for six hours before executing). This could be useful for lots of things other than TTL, such as scheduled refresh or updates as well. Although for something like drift, notifications are just as important if not more so than the schedule. 

Curious if you have thoughts on any of those workflows @mastoj

**Comment by mastoj** [comment]
I sure do :)

1. This would be my preferred way since it seems flexible and put me in control.
2. I think this depends on how you set it on the stack. If it is part of the config I don't like it since then you would need to check in a config for an ephemeral config file, but if set in some other way it could work.
3. This is definitely interesting and think that could also be an implementation detail of 1 for example, that is, if you implement this you could then also implement 1 which would just be to make a scheduled run after a deployment.

**Comment by meagancojocar** [comment]
Really excited to announce that we shipped Time-To-Live Stacks in Pulumi Cloud! https://www.pulumi.com/blog/ttl/

Open a new issue if you have any feedback or run into any issues.
