### ISSUE TITLE
https://app.pulumi.com/ is getting increasingly slow as our projects grow in size

### ISSUE THREAD

**Issue by SeanSanker** [pulumi/pulumi-cloud-requests#154]
As our stacks get into >1k resources, loading each page is taking many seconds making some people on my team think the dashboard is broken, and thus give up and don't use it.

We'd very much like to address these issues.

It may help to at least show some sort of loading spinner or skeleton loading UI.

**Comment by meagancojocar** [comment]
Hi @SeanSanker, thank you for this feedback! Are you finding all pages are slow or just the Stacks page? We have an existing issue open to add pagination to the Stacks page which we hope to get to next quarter: https://github.com/pulumi/service-requests/issues/56. If this addresses your pain point, I can close this out as a duplicate.

**Comment by tobiashenkel** [comment]
I have a similar issue (using pulumi self hosted service). Loading the main page of a large stack is very slow.

From my browser request log the slowest requests on a sample stack are:
* overview endpoint of the stack: 74MB, 14s
* overview endpoint of the stack: 74MB, 17s
* latest endpoint of the stack: 74MB, 11s

Overall statistics:
* 230MB transferred
* 40s until the page is fully loaded

It looks like it's transferring complete states three times when loading a stack overview page.

**Comment by djgrove** [comment]
@tobiashenkel thank you for passing us this feedback. Your comment absolutely caught the engineering team's attention, and we will be adding this to our upcoming sprint work.

**Comment by caseyyh** [comment]
Launching investigation in https://github.com/pulumi/pulumi-service/issues/13249

**Comment by caseyyh** [comment]
Hi @SeanSanker and @tobiashenkel  -- We merged a few fixes & optimizations in the past week or so that should help performance with this page, thanks for bringing this to our attention! I'm estimating latency improvements should be at about ~70%, so I'm closing out this issue for now, but please feel free to reopen if you're still seeing continued performance pains with the stacks page.

Once again, thanks for the feedback!
