### ISSUE TITLE
Change user timezone in the Pulumi dashboard 

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud-requests#158]
I notice that all time zones in the Activity tab of the Pulumi dashboard are set to GMT, which is problematic for me because I work in the AEST time zone. 

![image](https://user-images.githubusercontent.com/1161681/210664578-d7a48a43-a09d-4853-bce2-cf8780c4c113.png)

![image](https://user-images.githubusercontent.com/1161681/210665408-96d9cec4-232a-4093-b353-7eeb749d4245.png)

![image](https://user-images.githubusercontent.com/1161681/210665538-df1c3ea2-628b-4a84-a6a5-ea48780ccbcc.png)

This setting doesn't seem to be modifiable via my account settings. Can this be modified at all?

## Affected feature

* Stack list as shown on the project's page.
* Stacks activity tab
* Stack overview tab

**Comment by geekflyer** [comment]
I had a look at the frontend code running in the browser that formats these popups.
So what it actually calls is `date.toUTCString()` on all the timestamps returned from the backend, hence everything gets displayed in GMT/UTC (apparently GMT/UTC is practically the same).

If we change this to `date.toLocaleString(undefined,{timeZoneName: 'short'})` the output would be displayed in the users timezone (incl. the timezone name appended for explicitness).

I.e.:
```js
const timestampReturnedFromBackend = 1716239060000;

// current formatting
timestampReturnedFromBackend.toUTCString(); // -> returns 'Mon, 20 May 2024 21:04:20 GMT'

// proposed formatting
timestampReturnedFromBackend.toLocaleString(undefined, {timeZoneName: 'short'}); // -> return '5/20/2024, 2:04:20 PM PDT'  (for US users in pacific timezone).
```

I.e. it should be a relatively minor frontend change.

**Comment by caseyyh** [comment]
Thank you for filing this ticket!

We are going to take this issue back with our product + user experience team to identify what we want our default experience should be regarding time zones (local vs UTC), and any configurable options that we'd like to take.

**Comment by aureq** [comment]
Thanks a lot @kimberleyamackenzie 💚

**Comment by kimberleyamackenzie** [comment]
@aureq Yes, of course!  We handle time in many different little pockets of code across the codebase - so, I believe my PR corrected all the instances you named in this ticket, but if you see other places where it's wrong just open a ticket and tag me and I will get it fixed up!  Have also documented in our internal UX/UI guidance that local should be the default whenever adding timestamps or dates going forward.
