### ISSUE TITLE
Support the ability to set an expiration period for Pulumi Access Tokens

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-cloud-requests#160]
## Affected feature
As a Pulumi admin, I'd like to be able to set an  arbitrary expiration period for Pulumi Access Tokens. This allows me to enforce a rotation of my access tokens, which enhances the security of my Pulumi org(s).

**Comment by caseyyh** [comment]
This is done: https://www.pulumi.com/blog/short-lived-access-tokens/
