### ISSUE TITLE
Pulumi Deployments - Post to slack on failure

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-cloud-requests#168]
It would be nice if we could configure failed deployments to automatically post to slack. We have existing plans to integrate pulumi deployments into webhooks, but dedicated 1-click slack integration would be much nicer than having to deploy a lambda/webserver to process webhooks.

**Comment by EvanBoyle** [comment]
It is possible that we might be able to accomplish this with post-run-commands.

**Comment by pgavlin** [comment]
> It is possible that we might be able to accomplish this with post-run-commands.

This would require a little bit of work in the underlying workflow system as well, since right now any failure is a hard stop.

**Comment by komalali** [comment]
We've done this work with slack-formatted webhooks and deployment events.
