### ISSUE TITLE
Consider a way to centralize common Pulumi Deployment configuration info for a project. 

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-cloud-requests#169]
For a project with multiple stacks, I find myself restating/copypasting the same prerun commands and certain environment variables over and over again. It would be nice if there was a way to centralize common Pulumi Deployments configuration. 

Lots of options here, but one thing to consider might be reading deployment configuration first from Pulumi.yaml, and then from Pulumi.stack.yaml for overrides. I'm not entirely sure how this would work as we'd have to acquire those files before we do anything that depends on configuration.

**Comment by EvanBoyle** [comment]
This might be a good opportunity to utilize the pulumi service provider: https://github.com/pulumi/pulumi-pulumiservice/issues/97

**Comment by komalali** [comment]
This is included in the latest version of the pulumiservice provider: https://www.pulumi.com/registry/packages/pulumiservice/api-docs/deploymentsettings/
