### ISSUE TITLE
Programmatically create team access tokens

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-cloud-requests#172]
Team Access Token
## Affected feature
Team Access Token

Programmatically create team tokens team access tokens.
This would help with token rotation.

**Comment by EvanBoyle** [comment]
@tusharshahrs we have an API that allows creating team access tokens. It doesn't look like there are docs. The route is `/orgs/{orgName}/teams/{teamName}/tokens` and the payload just takes a `name` and `description`.

@djgrove I can't seem to find API docs for org tokens or team tokens, did we ever ship those?

**Comment by caseyyh** [comment]
Captured in https://www.pulumi.com/docs/pulumi-cloud/cloud-rest-api/#create-team-access-token

Marking as complete
