### ISSUE TITLE
Add built-in drift detection with Pulumi Deployments

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-cloud-requests#173]
Pulumi Deployments make it easy to build drift detection and we have examples for this: https://github.com/pulumi/deploy-demos/tree/main/pulumi-programs/drift-detection

We should build it into the product so that it is as easy as flipping a switch once Pulumi Deployments is configured for a stack.

**Comment by EvanBoyle** [comment]
The deployments launch blog goes into a little more detail on the drift example: https://www.pulumi.com/blog/pulumi-deployments/

**Comment by meagancojocar** [comment]
Thrilled to announce we shipped this! https://www.pulumi.com/blog/drift-detection/

Open an issue if you have any feedback!
