### ISSUE TITLE
Pulumi Deployments: Support private images for custom executor images

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-cloud-requests#196]
There should be a way to provide credentials for private docker images using environment variables or a similar mechanism.

**Comment by agibralter** [comment]
Alternatively, could there be a Dockerfile specified in the repo which could be built (and cached) on the fly?

**Comment by EvanBoyle** [comment]
In addition, we should support configuring the executor image from the console (I don't see this field in the form today) and make sure we have support in the provider.

**Comment by komalali** [comment]
>we should support configuring the executor image from the console (I don't see this field in the form today

FWIW, this is already supported
<img width="394" alt="Screenshot 2023-05-17 at 10 26 21 AM" src="https://github.com/pulumi/pulumi-cloud-requests/assets/24326455/69f83fa3-5229-4a12-b7e9-8bd486455cf6">

**Comment by pgavlin** [comment]
Support for image credentials has been released and is now available on the deployment settings page.
