### ISSUE TITLE
Add support for ephemeral PR environments to Pulumi Deployments

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-cloud-requests#206]
It should be possible to have a temporary stack created (and later cleaned up) per open PR against branch that contains deployment settings. It would be nice if these stacks also had an expiration date, or similar capabilities described in https://github.com/pulumi/service-requests/issues/149, that way if a PR sits open and gets stale, the infrastructure is reclaimed in the background (pushing a new commit to the PR would cause the environment to get reprovisioned). 

An interesting way to think about modeling could be a second set of settings that are attached to a stack as a sort of template, including OIDC config. When we process a github webhook, these templates could be treated as another node in the settings graph that we search over. When we encounter them we create a new stack with a randomly suffixed name, create a settings object for that stack based on the template, and kick off the initial deployment. One piece of nuance is that we'd likely want both a preview against the main stack as well as an update against the ephemeral stack to run on each commit that gets pushed, along with corresponding PR comments.

**Comment by mastoj** [comment]
I think just having ephemeral environments as a start take you a long way. With that in place would make it possible create them over API, the PR integration can be done as a second step. 

The ephemeral environments was what held us back from the deployments api since we wanted to create on commits to a PR but only have it up for a day or so, even if the PR was longer. The idea was then to create another GitHub action that listens to comments in the PR to deploy a new version at a later stage if someone wrote "DEPLOY" or something.

**Comment by EvanBoyle** [comment]
Some things to consider:
1. It would be nice if these environments could be stood up outside of the PR lifecycle. for instance via API (maybe even console?)
2. It would be nice if these environments had support for specifying a TTL (destroy after one day of inactivity, redeploy on new git push or other event)
3. The configuration and even the source code for an ephemeral environment might differ from the source stack. For instance production may have a dedicated database, but the ephemeral preview env might use a shared DB or a different instance size.

**Comment by EvanBoyle** [comment]
Today we shipped [Review Stacks](https://www.pulumi.com/docs/pulumi-cloud/deployments/review-stacks/) - dedicated cloud environments that get created automatically every time a pull request is opened, all powered by [Pulumi Deployments](https://www.pulumi.com/docs/pulumi-cloud/deployments). Open a pull request, and Pulumi Deployments will stand up a stack with your changes and the Pulumi GitHub App will add a PR comment with the outputs from your deployment. Merge the PR and Pulumi Deployments will destroy the stack and free up the associated resources.

https://www.pulumi.com/blog/review-stacks/

Follow up work to add a TTL workflow is tracked here: https://github.com/pulumi/pulumi-cloud-requests/issues/149
