### ISSUE TITLE
Pulumi Deployments: publish worker ip ranges

### ISSUE THREAD

**Issue by mvgijssel** [pulumi/pulumi-cloud-requests#208]
To lock down ingress access from the Pulumi Deployment workers to the internal infrastructure it would be nice if the ip ranges of the deployment workers are published somewhere. Bonus points for making these ip ranges available through a (public) api endpoint.

## Affected feature

Pulumi Deployment

**Comment by cleverguy25** [comment]
https://www.pulumi.com/docs/support/faq/#which-domains-and-ips-should-i-allowlist

**Comment by stooj** [comment]
This faq has moved.

Now at https://www.pulumi.com/docs/pulumi-cloud/faq/#which-domains-and-ips-should-i-allowlist
