### ISSUE TITLE
Gating mechanism for Deployments

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-cloud-requests#212]
In GitHub actions or other CI/CD systems, I can specify gating/approval flows on deployments.

Imagine I have 3 stacks, targeting my development, staging and production accounts.

I want to:

- Have previews for all accounts/stacks on PR
- Have development and staging deploy
- Have a manual approval process OR a smoke test mechanism for production deployments

As it currently stands, deployments deploys all stacks on PR

**Comment by komalali** [comment]
Closing this issue as this issue is partially supported and I've opened individual issues for the individual pieces that are not yet supported (#378 and #467)
