### ISSUE TITLE
Provide cross-stack resource search

### ISSUE THREAD

**Issue by sprsquish** [pulumi/pulumi-cloud-requests#24]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Trying to find all of the instances of a particular resource across all stacks is a labor intensive process that requires jumping from stack to stack in the UI. Being able to search for resources across all stacks in an org would make it much easier to answer questions like "where are all my VPC network resources?"

### Affected area/feature

Console

**Comment by EvanBoyle** [comment]
Thanks @sprsquish this is something that is on our radar, but we don't have a timeline yet.

**Comment by EvanBoyle** [comment]
Resource search shipped last week. Give it a try and let us know what you think! 

- [Launch blog](https://www.pulumi.com/blog/pulumi-insights/)
- [Documentation](https://www.pulumi.com/docs/intro/insights/search/)
