### ISSUE TITLE
Support Webauthn as 2FA / MFA when accessing the Pulumi Console

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud-requests#52]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The Pulumi service supports many ways for a user to authenticate. Namely, email/password, github, gitlab, saml/sso and atlassian. However, attacks are getting more and more sophisticated like [BitB](https://mrd0x.com/browser-in-the-browser-phishing-attack/) that can be difficult to detect. 

A possible additional protection would be to allow users to register one or more security key and prompt the user to tap their key to verify it's really them. The default prompt frequency could be set to once a day, but this could be tuned for customers part of a Pulumi organization.

Furthermore, this protection should be available to all Pulumi users, regardless of their identity provider (since Pulumi can't know if 2FA is used/enforced for these users)

### Affected area/feature

* Pulumi service

**Comment by meagancojocar** [comment]
Letting all that upvoted this know that we are watching this feature and plan to ship it this quarter!

**Comment by meagancojocar** [comment]
This has shipped! See details in [the blog post](https://www.pulumi.com/blog/multi-factor-auth-mfa-in-pulumi-cloud/).
