### ISSUE TITLE
Undelete/Recover deleted stacks

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud-requests#60]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It can be quite easy for a Pulumi user to delete one of their stacks by mistake (`pulumi stack rm`, not `destroy`). It would be great if the Pulumi service could offer a *Trash* feature where users could self-service and recover/undelete stack they accidentally deleted. The trash could offer to retain a deleted stack information for up to 30 days upon which stack states would be purged for the Pulumi service for good.

If this feature could also be integrated with the Pulumi CLI this would become really helpful to many people.

Other things to consider:
* Restoring the stack in-place
* Restoring the stack in a separate project
* Exporting the delete stack state file directly from the trash

### Affected area/feature

* Pulumi Service
* Pulumi CLI

**Comment by susanev** [comment]
also wonder if we should take a look at the user experience of deleting a stack, and see if there are ways we can improve the experience so folks don't delete stacks by accident.

**Comment by aureq** [comment]
@susanev I opened an issue related to stack deletion #48

**Comment by aureq** [comment]
Related customer issues

* https://github.com/pulumi/customer-support/issues/946
* https://github.com/pulumi/customer-support/issues/996
* https://github.com/pulumi/customer-support/issues/898
* https://github.com/pulumi/customer-support/issues/807
* https://github.com/pulumi/customer-support/issues/709

**Comment by EvanBoyle** [comment]
This feature is now available! https://www.pulumi.com/blog/restore-stacks/
