### ISSUE TITLE
Show access token creation date in settings page

### ISSUE THREAD

**Issue by austinbyers** [pulumi/pulumi-cloud-requests#64]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When looking at my personal Pulumi access tokens in the web app, I'd like to know when they were created. This information is added for tokens created by `pulumi login` in the description, but it isn't available for tokens created manually. Knowing how old a token is helps us know when it needs to be rotated or what it might have been used for

### Affected area/feature

Pulumi Web service

**Comment by lukehoban** [comment]
Very good suggestion - I've wanted this myself in the past!
