### ISSUE TITLE
Add filters to audit logs

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/pulumi-cloud-requests#85]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

From in-console user feedback: It would be nice if the new console's Audit logs had a search or filter feature.. If i want to see what a specific user did, i have to manually search through the logs and also keep hitting "Show more" to grab more data.

**Comment by EvanBoyle** [comment]
Audit logs do allow you to filter a users actions by clicking on their profile picture in the search results. Not the most obvious, but the feature does exist.

**Comment by ericrudder** [comment]
what do you think about maybe updating
https://www.pulumi.com/docs/intro/pulumi-cloud/audit-logs/ with a paragraph
and maybe a screenshot?
